#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=InstallEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=00:40:00
#SBATCH --output=/home/scur2553/uvadlc_practicals_2025/assignment2/part3/exercise_GCN_3_4_e_%A.out

module purge
module load 2025
module load Anaconda3/2025.06-1

cd $HOME/uvadlc_practicals_2025/assignment2/part3
source activate dl2025

srun python train.py --model 'matrix-gcn'
