#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=InstallEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=00:59:00
#SBATCH --output=/home/scur2553/uvadlc_practicals_2025/assignment3/part1/exercise_1_8_%A.out

module purge
module load 2025
module load Anaconda3/2025.06-1

cd $HOME/uvadlc_practicals_2025/assignment3/part1
source activate dl2025

srun python train_pl.py

