#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=InstallEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=04:00:00
#SBATCH --output=/home/scur2553/uvadlc_practicals_2025/assignment2/part2/exercise_2_7_%A.out

module purge
module load 2025
module load Anaconda3/2025.06-1

cd $HOME/uvadlc_practicals_2025/assignment2/part2
source activate dl2025

srun python train.py

